import Link from 'next/link'
import { ArrowLink, NewsletterForm, SectionHeading, SiteShell } from '@/components/site'
import { serviceItems } from '@/lib/content'

export const metadata = { title: 'The Inner Arc — Tarot for the questions that matter', description: 'Thoughtful tarot readings for reflection, direction, and the questions that stay with you.' }

export default function Home() {
  return <SiteShell><main>
    <section className="relative overflow-hidden border-b border-border/60"><div className="absolute inset-0"><img src="/images/hero-cards-candles.jpg" alt="" className="h-full w-full object-cover opacity-45" /></div><div className="absolute inset-0 bg-gradient-to-r from-background via-background/80 to-transparent" /><div className="relative mx-auto flex min-h-[620px] max-w-7xl items-center px-6 py-24 lg:min-h-[700px] lg:px-10"><div className="max-w-3xl"><p className="mb-7 text-xs uppercase tracking-[0.3em] text-accent">A considered approach to tarot</p><h1 className="max-w-3xl font-serif text-6xl leading-[0.96] tracking-tight text-foreground md:text-8xl text-balance">Make room for what you already know.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground">Private readings for moments of change, curiosity, and return. Not a prediction — a place to hear yourself more clearly.</p><div className="mt-10 flex flex-wrap items-center gap-6"><Link href="/services" className="rounded-full bg-primary px-7 py-3.5 text-sm font-medium text-primary-foreground transition-transform hover:-translate-y-0.5">Explore readings</Link><ArrowLink href="/about-tarot">What is tarot?</ArrowLink></div></div><div className="absolute bottom-12 right-12 hidden h-40 w-40 rounded-full border border-accent/50 lg:block"><div className="absolute inset-5 rounded-full border border-accent/30" /><span className="absolute left-1/2 top-1/2 h-1.5 w-1.5 -translate-x-1/2 -translate-y-1/2 rounded-full bg-accent" /></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><SectionHeading eyebrow="A different kind of reading" title="A mirror, not a map.">Tarot gives shape to the questions we carry. Through symbol, story, and a little spaciousness, it can help you notice what has been asking to be seen.</SectionHeading><div className="lg:justify-self-end"><ArrowLink href="/about-tarot">Learn more about tarot</ArrowLink></div></div></section>
    <section className="border-y border-border/60 bg-card"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><SectionHeading eyebrow="The reading room" title="Come as you are. Leave with a little more clarity." /><div className="mt-14 grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2 lg:grid-cols-4">{serviceItems.map((item, index) => <div key={item.title} className="bg-card p-7"><span className="font-mono text-xs text-accent">0{index + 1}</span><h3 className="mt-16 font-serif text-2xl text-foreground">{item.title}</h3><p className="mt-3 text-xs uppercase tracking-[0.16em] text-accent">{item.category}</p><p className="mt-5 text-sm leading-6 text-muted-foreground">{item.description}</p></div>)}</div><div className="mt-8"><ArrowLink href="/services">View all readings</ArrowLink></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr]"><SectionHeading eyebrow="Kind words" title="A reading can become a new way of listening." /><div className="grid gap-6 md:grid-cols-2"><figure className="border-l border-accent pl-6"><blockquote className="font-serif text-2xl leading-9 text-foreground">“I left with fewer answers, in the best possible way — and a much better question.”</blockquote><figcaption className="mt-6 text-xs uppercase tracking-[0.18em] text-muted-foreground">— M., written reading</figcaption></figure><figure className="border-l border-accent pl-6"><blockquote className="font-serif text-2xl leading-9 text-foreground">“It felt grounded, generous, and strangely practical. I could feel my next step.”</blockquote><figcaption className="mt-6 text-xs uppercase tracking-[0.18em] text-muted-foreground">— A., The Open Road</figcaption></figure></div></div></section>
    <section className="relative border-t border-border/60"><div className="absolute inset-0"><img src="/images/section-candle-tall.jpg" alt="" className="h-full w-full object-cover opacity-15" /></div><div className="absolute inset-0 bg-card/85" /><div className="relative mx-auto flex max-w-7xl flex-col gap-8 px-6 py-20 lg:flex-row lg:items-center lg:justify-between lg:px-10"><div><p className="text-xs uppercase tracking-[0.25em] text-accent">Notes from the inner arc</p><h2 className="mt-3 font-serif text-4xl text-foreground">A little perspective, occasionally.</h2></div><NewsletterForm /></div></section>
  </main></SiteShell>
}
