'use client'

import { useState } from 'react'

const focusAreas = ['Love & relationships', 'Career & purpose', 'Life & direction', 'Shadow work']
export function PartnerApplicationForm() {
  const [submitted, setSubmitted] = useState(false)
  if (submitted) return <div className="border border-accent/60 bg-card p-8"><p className="text-xs uppercase tracking-[0.2em] text-accent">Application received</p><h2 className="mt-4 font-serif text-3xl text-foreground">Thank you for introducing yourself.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">We&apos;ll read through your details and be in touch if it feels like a thoughtful fit.</p></div>
  return <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }} className="space-y-6"><div className="grid gap-6 sm:grid-cols-2"><label className="text-sm text-muted-foreground">Full name<input required name="name" className="mt-2 w-full border border-border bg-background px-4 py-3 text-foreground outline-none focus:border-accent" /></label><label className="text-sm text-muted-foreground">Email<input required type="email" name="email" className="mt-2 w-full border border-border bg-background px-4 py-3 text-foreground outline-none focus:border-accent" /></label></div><label className="block text-sm text-muted-foreground">Years of experience reading tarot<input required type="number" min="0" name="years" className="mt-2 w-full border border-border bg-background px-4 py-3 text-foreground outline-none focus:border-accent" /></label><fieldset><legend className="text-sm text-muted-foreground">Specialty or focus areas</legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{focusAreas.map((area) => <label key={area} className="flex items-center gap-3 text-sm text-foreground"><input type="checkbox" name="focus" value={area} className="accent-accent" />{area}</label>)}</div></fieldset><label className="block text-sm text-muted-foreground">Short bio / why you&apos;d like to join<textarea required name="bio" rows={6} className="mt-2 w-full resize-none border border-border bg-background px-4 py-3 text-foreground outline-none focus:border-accent" /></label><label className="block text-sm text-muted-foreground">Portfolio or social link <span className="text-xs">(optional)</span><input type="url" name="link" className="mt-2 w-full border border-border bg-background px-4 py-3 text-foreground outline-none focus:border-accent" /></label><button className="rounded-full bg-primary px-6 py-3 text-sm font-medium text-primary-foreground transition-transform hover:-translate-y-0.5">Send application</button></form>
}
