import { sanityFetch } from '@/sanity/lib/fetch'
import { partnersQuery, partnerBySlugQuery } from '@/sanity/lib/queries'

export type Partner = { name: string; slug: string; photo: string; specialty: string; tags: string[]; yearsExperience: number; featured: boolean; bio: string; approach: string; readings: string[]; testimonial: { quote: string; name: string } }
export const partnerFilters = ['All readers', 'Love & relationships', 'Career & purpose', 'Life & direction', 'Shadow work']

export const partners: Partner[] = [
  { name: 'Mara Ellison', slug: 'mara-ellison', photo: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=700&q=85', specialty: 'Love, timing, and the honest conversation', tags: ['Love & relationships', 'Life & direction'], yearsExperience: 12, featured: true, bio: 'Mara reads for the places where feeling and choice meet. Her sessions are warm, direct, and quietly practical.', approach: 'I see tarot as a mirror with a little more vocabulary.', readings: ['Two of Us', 'The Open Road', 'A Quiet Question'], testimonial: { quote: 'Mara helped me ask a kinder, clearer question.', name: 'Eleanor R.' } },
  { name: 'Jon Bell', slug: 'jon-bell', photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=85', specialty: 'Career transitions and creative purpose', tags: ['Career & purpose', 'Life & direction'], yearsExperience: 9, featured: true, bio: 'Jon brings a grounded, curious energy to readings about work and direction.', approach: 'The cards help us see the decision from a wider place.', readings: ['The Next Chapter', 'The Open Road'], testimonial: { quote: 'A generous reading that made a complicated choice feel possible.', name: 'Mina T.' } },
  { name: 'Priya Shah', slug: 'priya-shah', photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=700&q=85', specialty: 'Inner patterns and shadow work', tags: ['Shadow work', 'Life & direction'], yearsExperience: 15, featured: false, bio: 'Priya creates a spacious container for the questions beneath the question.', approach: 'Nothing in a spread is an instruction. It is an invitation.', readings: ['A Quiet Question', 'The Open Road'], testimonial: { quote: 'Priya held the reading with so much care.', name: 'Sofia K.' } },
  { name: 'Theo Martin', slug: 'theo-martin', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=85', specialty: 'Relationships, boundaries, and new beginnings', tags: ['Love & relationships', 'Shadow work'], yearsExperience: 7, featured: false, bio: 'Theo reads with an easy, conversational style.', approach: 'I want a reading to leave you more in conversation with yourself.', readings: ['Two of Us', 'A Quiet Question'], testimonial: { quote: 'The reading gave language to something I had been circling.', name: 'Cal M.' } },
  { name: 'Nia Okafor', slug: 'nia-okafor', photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=85', specialty: 'Life direction and fresh perspective', tags: ['Life & direction', 'Career & purpose'], yearsExperience: 10, featured: false, bio: 'Nia offers clear-eyed, encouraging readings for periods of change.', approach: 'A card can be a question, a permission slip, or a pause.', readings: ['The Open Road', 'The Next Chapter'], testimonial: { quote: 'Nia made the future feel less like a test.', name: 'Daniel W.' } },
]

export function getPartner(slug: string) { return partners.find(p => p.slug === slug) }
export async function getPartners(): Promise<Partner[]> { const d = await sanityFetch<Partner[]>(partnersQuery); return d?.length ? d : partners }
export async function getPartnerBySlug(slug: string): Promise<Partner | null> { const d = await sanityFetch<Partner>(partnerBySlugQuery, { slug }); return d || getPartner(slug) || null }
